#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git branch --show-current)
if [ "$current_branch" = "main" ]; then
    echo "Direct commits to the main branch are not allowed. Please create a new branch for your changes."
    exit 1
fi

npm test
if [ $? -ne 0 ]; then
    echo "Tests failed. Fix errors before committing."
    exit 1
fi

npm run lint
if [ $? -ne 0 ]; then
    echo "Linting errors found. Fix errors before committing."
    exit 1
fi

echo "Reminder: Make sure you've branched off the main branch!"
echo "Reminder: Ensure all tests pass and ESLint errors are cleared before committing."
